title: Chen Guiming's Homepage
page-top-title: Chen Guiming
top-section-bg-text: Computer Science
home-subtitle: Chen Guiming&ensp;|&ensp;陈桂明
copyright-text: '&copy; Chen Guiming 2022-2026. All Rights Reserved.'
